#默认数据库连接配置
user:
  jpa:
     show-sql: true
     hibernate:
        ddl-auto: create
        
  datasource:
    
    type: com.mysql.jdbc.Driver
    #url:  jdbc:mysql://localhost:3306/crazychain_db?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    url: jdbc:h2:./crazychain_db
    username: root
    password: 123456

    
  #thymeleaf:
  #  mode: HTML5
  
second:
  jpa:
     show-sql: true
     hibernate:
        ddl-auto: create
  datasource:
   
    type: com.mysql.jdbc.Driver
    #url:  jdbc:mysql://192.168.10.12:3306/article_db?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    url: jdbc:h2:./article_db
    username: root
    password: MyNewPass4!
   
  #字符集和json格式工具
  http:
    encoding:
      charset: utf-8
    converters:
      preferred-json-mapper: jackson
    multipart:
      max-file-size: 10MB
  application:
    name: crazychain

